//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::bot::Entity as Bot;
pub use super::channel::Entity as Channel;
pub use super::chat_message::Entity as ChatMessage;
pub use super::user::Entity as User;
pub use super::watch_time::Entity as WatchTime;
