[workspace]
members = [
    "database",
    "cache",
    "websocket",
    "parser",
    "auth",
    "twitch-api",
    "bot-watch-time",
    "bot-message-saver",
    "bot-token-validator",
]
resolver = "2"
